---
kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: build
    image: docker
    environment:
      DOCKER_ORG:
        from_secret: docker_org
      DOCKER_TOKEN:
        from_secret: docker
    commands:
      - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ORG" --password-stdin
      - cd demo
      - docker build -t ${DOCKER_ORG}/helene:latest .
      - docker push ${DOCKER_ORG}/helene:latest

  - name: deploy
    image: bitnami/kubectl
    environment:
      K8S_CONFIG:
        from_secret: kubeconfig
    when:
      branch:
        - staging
    commands:
      - echo "$K8S_CONFIG" > /.kube/config
      - kubectl rollout restart deployment/helene-app

  - name: notify
    image: plugins/slack
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    settings:
      channel: cicd
      webhook: ${SLACK_WEBHOOK}
