name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Node.js Tests
    services:
      redis:
        image: redis:7.2-alpine
        ports:
          - 6379:6379
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test --run
      - run: yarn run browser:test --run
        env:
          CI: true

