name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_node:
    name: Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: supercharge/redis-github-action@1.4.0
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: lerna run build
      - run: lerna run node:test:mocha
        env:
          CI: true
