name: Test
on:
  push:
    branches:
      - main
      - staging
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: supercharge/redis-github-action@1.4.0
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-frozen-lockfile
      - run: pnpm run test:mocha
        env:
          CI: true
